name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dart-lang/setup-dart@v1
    - run: dart pub get
    - run: dart format --set-exit-if-changed --output=none .
    - run: dart analyze
    - run: dart test
